# Copyright 2023-2026 Playlab/ACAL
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#!/usr/bin/env python3
"""
SST Multi-Device Configuration
Generated by generate_sst_config.py

Number of devices: 4
"""

import sst

# Enable SST statistics
sst.setStatisticLoadLevel(7)
sst.setStatisticOutput("sst.statOutputConsole")

# QEMU Binary Component
qemu = sst.Component("qemu", "qemubinary.QEMUBinary")
qemu.addParams({"clock": "1GHz"})
qemu.addParams({"verbose": 2})
qemu.addParams({"binary_path": "../riscv-programs/multi_device_test.elf"})
qemu.addParams({"qemu_path": "qemu-system-riscv32"})
qemu.addParams({"socket_path": "/tmp/qemu-sst-mmio.sock"})
qemu.addParams({"num_devices": 4})
qemu.addParams({"device0_base": "0x10200000"})
qemu.addParams({"device0_size": 4096})
qemu.addParams({"device0_name": "echo_device"})
qemu.addParams({"device1_base": "0x10300000"})
qemu.addParams({"device1_size": 4096})
qemu.addParams({"device1_name": "compute_device"})
qemu.addParams({"device2_base": "0x10400000"})
qemu.addParams({"device2_size": 4096})
qemu.addParams({"device2_name": "echo_device2"})
qemu.addParams({"device3_base": "0x10500000"})
qemu.addParams({"device3_size": 4096})
qemu.addParams({"device3_name": "compute_device2"})

# Device Components
# Device 0: echo_device
echo_device = sst.Component("echo_device", "acalsim.QEMUDevice")
echo_device.addParams({"clock": "1GHz"})
echo_device.addParams({"verbose": 2})
echo_device.addParams({"echo_latency": 10})

# Device 1: compute_device
compute_device = sst.Component("compute_device", "acalsim.ComputeDevice")
compute_device.addParams({"clock": "1GHz"})
compute_device.addParams({"verbose": 2})
compute_device.addParams({"compute_latency": 100})

# Device 2: echo_device2
echo_device2 = sst.Component("echo_device2", "acalsim.QEMUDevice")
echo_device2.addParams({"clock": "1GHz"})
echo_device2.addParams({"verbose": 2})
echo_device2.addParams({"echo_latency": 5})

# Device 3: compute_device2
compute_device2 = sst.Component("compute_device2", "acalsim.ComputeDevice")
compute_device2.addParams({"clock": "1GHz"})
compute_device2.addParams({"verbose": 2})
compute_device2.addParams({"compute_latency": 50})

# Links between QEMU and devices
# Link 0: QEMU <-> echo_device
link0 = sst.Link("link_0")
link0.connect((qemu, "device_port_0", "1ns"), (echo_device, "cpu_port", "1ns"))

# Link 1: QEMU <-> compute_device
link1 = sst.Link("link_1")
link1.connect((qemu, "device_port_1", "1ns"), (compute_device, "cpu_port", "1ns"))

# Link 2: QEMU <-> echo_device2
link2 = sst.Link("link_2")
link2.connect((qemu, "device_port_2", "1ns"), (echo_device2, "cpu_port", "1ns"))

# Link 3: QEMU <-> compute_device2
link3 = sst.Link("link_3")
link3.connect((qemu, "device_port_3", "1ns"), (compute_device2, "cpu_port", "1ns"))

# Simulation parameters
sst.setProgramOption("stop-at", "100ms")
