/*
 * Copyright 2023-2026 Playlab/ACAL
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated by ACALSim PyTorch Backend
// Graph: graph_0
#ifndef GRAPH_0_H
#define GRAPH_0_H

#include <stdint.h>

// Device base addresses
#define ECHO_DEVICE_BASE    0x10200000
#define COMPUTE_DEVICE_BASE 0x10300000

// Compute device registers
#define REG_CMD      0x00
#define REG_STATUS   0x04
#define REG_DATA_IN  0x08
#define REG_DATA_OUT 0x0C
#define REG_SIZE     0x10
#define REG_RESULT   0x14

// Commands
#define CMD_NOP     0
#define CMD_LOAD    1
#define CMD_STORE   2
#define CMD_COMPUTE 3
#define CMD_MATMUL  4
#define CMD_CONV2D  5

// Tensor dimensions
#define INPUT_0_SIZE 64
#define INPUT_0_DIM0 4
#define INPUT_0_DIM1 16
#define PARAM_1_SIZE 512
#define PARAM_1_DIM0 16
#define PARAM_1_DIM1 32
#define T_2_SIZE     128
#define T_2_DIM0     4
#define T_2_DIM1     32
#define T_3_SIZE     128
#define T_3_DIM0     4
#define T_3_DIM1     32
#define PARAM_4_SIZE 512
#define PARAM_4_DIM0 32
#define PARAM_4_DIM1 16
#define T_5_SIZE     64
#define T_5_DIM0     4
#define T_5_DIM1     16
#define T_6_SIZE     64
#define T_6_DIM0     4
#define T_6_DIM1     16
#define PARAM_7_SIZE 128
#define PARAM_7_DIM0 16
#define PARAM_7_DIM1 8
#define T_8_SIZE     32
#define T_8_DIM0     4
#define T_8_DIM1     8

// Function declarations
void graph_0_init(void);
void graph_0_forward(float* inputs, float* outputs);
void graph_0_cleanup(void);

#endif  // GRAPH_0_H
