#!/usr/bin/env python3
"""
SST Multi-Device Configuration Generator

Generates SST Python configuration files for QEMU with N devices.
Supports both declarative device specifications and programmatic generation.

Usage:
    python3 generate_sst_config.py --devices config.json --output test.py
    python3 generate_sst_config.py --num-devices 4 --output test.py
"""

import argparse
import json
import sys
from typing import List, Dict, Any


class DeviceSpec:
    """Specification for a single SST device"""
    def __init__(self, name: str, base_addr: int, size: int, component: str, params: Dict[str, Any] = None):
        self.name = name
        self.base_addr = base_addr
        self.size = size
        self.component = component
        self.params = params or {}


class SSTConfigGenerator:
    """Generates SST configuration files for multi-device setups"""

    def __init__(self):
        self.devices: List[DeviceSpec] = []
        self.qemu_params = {
            "clock": "1GHz",
            "verbose": 2,
            "binary_path": "riscv-programs/hello.elf",
            "qemu_path": "qemu-system-riscv32",
            "socket_path": "/tmp/qemu-sst-mmio.sock"
        }

    def add_device(self, device: DeviceSpec):
        """Add a device to the configuration"""
        self.devices.append(device)

    def set_qemu_params(self, **params):
        """Update QEMU component parameters"""
        self.qemu_params.update(params)

    def generate_config(self, output_file: str):
        """Generate SST configuration file"""
        with open(output_file, 'w') as f:
            f.write(self._generate_header())
            f.write(self._generate_qemu_component())
            f.write(self._generate_devices())
            f.write(self._generate_links())
            f.write(self._generate_simulation())

    def _generate_header(self) -> str:
        """Generate file header with imports"""
        return """#!/usr/bin/env python3
\"\"\"
SST Multi-Device Configuration
Generated by generate_sst_config.py

Number of devices: {}
\"\"\"

import sst

# Enable SST statistics
sst.setStatisticLoadLevel(7)
sst.setStatisticOutput("sst.statOutputConsole")

""".format(len(self.devices))

    def _generate_qemu_component(self) -> str:
        """Generate QEMU component configuration"""
        lines = ["# QEMU Binary Component\n"]
        lines.append("qemu = sst.Component(\"qemu\", \"qemubinary.QEMUBinary\")\n")

        # Add parameters
        for key, value in self.qemu_params.items():
            if isinstance(value, str):
                lines.append(f'qemu.addParams({{\"{key}\": \"{value}\"}})\n')
            else:
                lines.append(f'qemu.addParams({{\"{key}\": {value}}})\n')

        # Add num_devices parameter
        lines.append(f'qemu.addParams({{\"num_devices\": {len(self.devices)}}})\n')

        # Add device-specific parameters
        for i, dev in enumerate(self.devices):
            lines.append(f'qemu.addParams({{\"device{i}_base\": \"0x{dev.base_addr:08x}\"}})\n')
            lines.append(f'qemu.addParams({{\"device{i}_size\": {dev.size}}})\n')
            lines.append(f'qemu.addParams({{\"device{i}_name\": \"{dev.name}\"}})\n')

        lines.append("\n")
        return "".join(lines)

    def _generate_devices(self) -> str:
        """Generate device component configurations"""
        lines = ["# Device Components\n"]

        for i, dev in enumerate(self.devices):
            lines.append(f"# Device {i}: {dev.name}\n")
            lines.append(f'{dev.name} = sst.Component(\"{dev.name}\", \"{dev.component}\")\n')

            # Add device parameters
            device_params = {
                "clock": "1GHz",
                "verbose": 2,
                **dev.params
            }

            for key, value in device_params.items():
                if isinstance(value, str):
                    lines.append(f'{dev.name}.addParams({{\"{key}\": \"{value}\"}})\n')
                else:
                    lines.append(f'{dev.name}.addParams({{\"{key}\": {value}}})\n')

            lines.append("\n")

        return "".join(lines)

    def _generate_links(self) -> str:
        """Generate SST links between QEMU and devices"""
        lines = ["# Links between QEMU and devices\n"]

        for i, dev in enumerate(self.devices):
            lines.append(f"# Link {i}: QEMU <-> {dev.name}\n")
            lines.append(f'link{i} = sst.Link(\"link_{i}\")\n')
            lines.append(f'link{i}.connect(\n')
            lines.append(f'    (qemu, \"device_port_{i}\", \"1ns\"),\n')
            lines.append(f'    ({dev.name}, \"cpu_port\", \"1ns\")\n')
            lines.append(f')\n\n')

        return "".join(lines)

    def _generate_simulation(self) -> str:
        """Generate simulation parameters"""
        return """# Simulation parameters
sst.setProgramOption("stop-at", "100ms")
"""


def load_devices_from_json(json_file: str) -> List[DeviceSpec]:
    """Load device specifications from JSON file"""
    with open(json_file, 'r') as f:
        data = json.load(f)

    devices = []
    for dev_data in data.get("devices", []):
        device = DeviceSpec(
            name=dev_data["name"],
            base_addr=int(dev_data["base_addr"], 16) if isinstance(dev_data["base_addr"], str) else dev_data["base_addr"],
            size=dev_data.get("size", 4096),
            component=dev_data.get("component", "acalsim.QEMUDevice"),
            params=dev_data.get("params", {})
        )
        devices.append(device)

    return devices


def generate_default_devices(num_devices: int, base_addr: int = 0x10200000, spacing: int = 0x100000) -> List[DeviceSpec]:
    """Generate N default echo devices with sequential addresses"""
    devices = []
    for i in range(num_devices):
        device = DeviceSpec(
            name=f"device{i}",
            base_addr=base_addr + (i * spacing),
            size=4096,
            component="acalsim.QEMUDevice",
            params={"echo_latency": 10}
        )
        devices.append(device)

    return devices


def main():
    parser = argparse.ArgumentParser(
        description="Generate SST multi-device configuration files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate config with 4 default devices
  python3 generate_sst_config.py --num-devices 4 --output qemu_4device_test.py

  # Generate config from JSON specification
  python3 generate_sst_config.py --devices my_devices.json --output qemu_custom_test.py

  # Generate config with custom QEMU binary
  python3 generate_sst_config.py --num-devices 2 --binary test.elf --output qemu_test.py

JSON Format:
{
  "devices": [
    {
      "name": "echo",
      "base_addr": "0x10200000",
      "size": 4096,
      "component": "acalsim.QEMUDevice",
      "params": {
        "echo_latency": 10
      }
    }
  ]
}
        """
    )

    parser.add_argument("--devices", help="JSON file with device specifications")
    parser.add_argument("--num-devices", type=int, help="Number of default devices to generate")
    parser.add_argument("--output", "-o", required=True, help="Output SST configuration file")
    parser.add_argument("--binary", help="Path to RISC-V binary (default: riscv-programs/hello.elf)")
    parser.add_argument("--base-addr", help="Base address for first device (default: 0x10200000)")
    parser.add_argument("--spacing", type=lambda x: int(x, 0), default=0x100000,
                        help="Address spacing between devices (default: 0x100000)")

    args = parser.parse_args()

    # Validate arguments
    if not args.devices and not args.num_devices:
        parser.error("Either --devices or --num-devices must be specified")

    # Create generator
    generator = SSTConfigGenerator()

    # Update QEMU parameters if specified
    if args.binary:
        generator.set_qemu_params(binary_path=args.binary)

    # Load or generate devices
    if args.devices:
        devices = load_devices_from_json(args.devices)
    else:
        base_addr = int(args.base_addr, 0) if args.base_addr else 0x10200000
        devices = generate_default_devices(args.num_devices, base_addr, args.spacing)

    # Add devices to generator
    for device in devices:
        generator.add_device(device)

    # Generate configuration
    generator.generate_config(args.output)

    print(f"Generated SST configuration: {args.output}")
    print(f"  Devices: {len(devices)}")
    for i, dev in enumerate(devices):
        print(f"    {i}: {dev.name} @ 0x{dev.base_addr:08x} ({dev.component})")


if __name__ == "__main__":
    main()
